AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API Gateway Lambda Example

Resources:

  Products:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Events:
        Person:
          Type: Api
          Properties:
            Path: /person/{id}
            Method: get
        Persons:
          Type: Api
          Properties:
            # Query parameters don't to be defined
            Path: /persons
            Method: get